DROP TABLE IF EXISTS review_likes;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS liked_film;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS rating;

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_5D PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS rating (
    rating_id INTEGER NOT NULL AUTO_INCREMENT,
    name_rating CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (rating_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING,
    email CHARACTER VARYING NOT NULL,
    login CHARACTER VARYING NOT NULL,
    birthday DATE,
    CONSTRAINT CONSTRAINT_6 PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING NOT NULL,
    description CHARACTER VARYING,
    release_date DATE,
    duration INTEGER,
    rating_id INTEGER NOT NULL,
    CONSTRAINT CONSTRAINT_5 PRIMARY KEY (film_id),
    CONSTRAINT CONSTRAINT_5C FOREIGN KEY (rating_id) REFERENCES rating(rating_id)
);

CREATE TABLE IF NOT EXISTS liked_film (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT CONSTRAINT_D FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT CONSTRAINT_D9 FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_friends (
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    status BOOLEAN,
    PRIMARY KEY (friend_id, user_id),
    CONSTRAINT CONSTRAINT_3 FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT CONSTRAINT_37 FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT CONSTRAINT_A FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT CONSTRAINT_A3 FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);
CREATE TABLE IF NOT EXISTS feed (
    event_id INTEGER NOT NULL AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    entity_id INTEGER NOT NULL,
    event_type CHARACTER VARYING NOT NULL,
    operation CHARACTER VARYING NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT feed_pk PRIMARY KEY (event_id),
    CONSTRAINT feed_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS reviews (
    review_id INTEGER NOT NULL AUTO_INCREMENT,
    content CHARACTER VARYING NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    useful INTEGER DEFAULT 0,
    CONSTRAINT reviews_pk PRIMARY KEY (review_id),
    CONSTRAINT reviews_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT reviews_film_fk FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS review_likes (
    review_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    is_useful BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT review_likes_review_fk FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE,
    CONSTRAINT review_likes_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

